apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "event-ingestor.fullname" . }}
spec:
{{ if eq .Values.global.environment "production"}}
  replicas: {{ .Values.global.ingestor.minReplicas | default 2 }}
{{ else }}
  replicas: 1
{{ end }}
  selector:
    matchLabels:
      chart: {{ include "event-ingestor.chart" . }}
  template:
    metadata:
      labels:
        chart: {{ include "event-ingestor.chart" . }}
        tier: backend
    spec:
      volumes:
        {{- if eq .Values.global.messageQueue.type "pubsub" }}
        - name: mr-platform-pubsub
          secret:
            secretName: mr-platform-pubsub
        {{- end }}
      containers:
        - name: event-api-container
          image: gcr.io/metarouter-cloud/event-api:rc0.1.0-beta
          {{- if eq .Values.global.environment "production"}}
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
            requests:
              cpu: ".5"
              memory: "2Gi"
          {{- end}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            {{- if eq .Values.global.messageQueue.type "pubsub" }}
            - name: mr-platform-pubsub
              mountPath: /var/secrets/google
            {{- end }}
          env:
            - name: EA_API_PORT
              value: "8080"
            - name: EA_ADMIN_PORT
              value: "true"
            - name: EA_DEBUG_MODE
              value: {{ .Values.global.ingestor.debugMode | default "false" | quote }}
            - name: EA_ENABLE_PPROF
              value: "true"
            - name: EA_ENABLE_HEALTH_CHECK
              value: {{ .Values.global.ingestor.healthCheck | default "true" | quote }}
            - name: EA_ENABLE_PROMETHEUS
              value: {{ .Values.global.prometheus.enabled | quote }}
            - name: EA_MESSAGE_WRITER
              value: {{ .Values.global.messageQueue.type | quote }}
            {{- if eq .Values.global.messageQueue.type "pubsub" }}
            - name: EA_GCP_PUB_SUB_PROJECT
              value: {{ .Values.global.messageQueue.groupId | quote }}
            - name: EA_GCP_PUB_SUB_TOPIC
              value: "{{ .Values.global.messageQueue.topicPrefix }}main"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
            {{- end }}
            {{- if eq .Values.global.messageQueue.type "kafka" }}
            - name: EA_KAFKA_BROKERS
              value: {{ .Values.global.messageQueue.broker | quote }}
            - name: EA_KAFKA_TOPIC
              value: "{{ .Values.global.messageQueue.topicPrefix }}main"
            {{- end }}
