apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.global.host | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if or (eq .Values.global.tls.type "self") (eq .Values.global.tls.type "clusterIssuer") }}
    kubernetes.io/tls-acme: {{ .Values.global.tls.acme | default "false" | quote }}
    certmanager.k8s.io/issuer: {{ .Values.global.tls.issuer | default "mr-platform-acme-issuer" | quote }}
    certmanager.k8s.io/acme-challenge-type: http01
    {{- end}}
spec:
  rules:
{{- if eq .Values.global.environment "production"}}
  - host: {{ .Values.global.host | quote }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "event-ingestor.fullname" . }}
            servicePort: 8080
{{- else }}
  - http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "event-ingestor.fullname" . }}
            servicePort: 8080
{{- end }}
{{- if eq .Values.global.environment "production"}}
  tls:
    {{- if eq .Values.global.tls.type "self" }}
    - secretName: mr-platform-acme
      hosts:
        - {{ .Values.global.host | quote }}
    {{- end }}
    {{- if eq .Values.global.tls.type "secret" }}
    - secretName: {{ .Values.global.tls.secretName | default "mr-platform-tls" | quote }}
      hosts:
        - {{ .Values.global.host | quote }}
    {{- end }}
{{- end }}

{{- if eq .Values.global.tls.type "self" }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Values.global.tls.issuer | default "mr-platform-acme-issuer" | quote }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.global.adminEmail | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.global.tls.issuer | default "mr-platform-acme-issuer" | quote }}
    # Enable the HTTP-01 challenge provider
    http01: {}
{{- end }}
