apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.global.host | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: {{ .Values.global.acme.issuer | quote }}
    certmanager.k8s.io/acme-challenge-type: http01
    kubernetes.io/tls-acme: {{ .Values.global.acme.enabled | default "false" | quote }}
spec:
  rules:
{{- if eq .Values.global.environment "production"}}
  - host: {{ .Values.global.host | quote }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "event-ingestor.fullname" . }}
            servicePort: 8080
{{- else }}
  - http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "event-ingestor.fullname" . }}
            servicePort: 8080
{{- end }}
{{- if eq .Values.global.environment "production"}}
  tls:
    {{- if .Values.global.acme.enabled }}
    - secretName: mr-platform-acme
      hosts:
        - {{ .Values.global.host | quote }}
    {{- end }}
    {{- if .Values.global.tlsSecret }}
    - secretName: mr-platform-tls
      hosts:
        - {{ .Values.global.host | quote }}
    {{- end }}
{{- end }}

{{- if .Values.global.acme.enabled }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.global.adminEmail | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.global.adminEmail | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    # Enable the HTTP-01 challenge provider
    http01: {}
{{- end }}
