# https://docs.helm.sh/developing_charts/#chart-dependencies
dependencies:
  - name: cert-manager
    version: 0.6.0
    repository: "https://kubernetes-charts.storage.googleapis.com/" #"@stable"
    condition: cert-manager.enabled
  - name: nginx-ingress
    version: ~1.2.3
    repository: "https://kubernetes-charts.storage.googleapis.com/" # "@stable"
    condition: nginx-ingress.enabled
  - name: prometheus
    version: 8.8.0
    repository: "https://kubernetes-charts.storage.googleapis.com/" # "@stable"
    condition: prometheus.enabled
  - name: grafana
    version: 2.2.1
    repository: "https://kubernetes-charts.storage.googleapis.com/" # "@stable"
    condition: grafana.enabled
