# https://docs.helm.sh/developing_charts/#chart-dependencies
dependencies:
  - name: cert-manager
    version: 0.6.0
    repository: "@stable"
    condition: cert-manager.enabled
  - name: nginx-ingress
    version: ~1.2.3
    repository: "@stable"
    condition: nginx-ingress.enabled
