global:
    host: jhfk # Host Name for EE Cluster
    adminEmail: mjgc # Admin Email for EE Cluster
    environment: local # local (minimal resources) or production (stable, failover resources)
    tls:
      type: "off"
    prometheus:
      enabled: false
    forwarders:
        enabled: true # Allow for built-in Data Forwarders to send events to 3rd Party API and data destinations.
        debugMode: true
        enabledDestinations: # Will create a duplicate Service and Deployment for each enabled destination, uses dependency to know which Destination logic to use. Omit the ones that shouldn't be running.
          - label: webhooks
            dependency: "@astronomerio/integration-webhooks"
        
        
        
        
    messageQueue:
        type: kafka # pubsub or kafka (msgbus and kinesis coming soon)
        topicPrefix: "mree-"
        groupId: "mr-ee"
        retention: "7d"
    ingestor:
      enabled: true # Allow for built-in API to receive data, false if another service is already feeding subscription the router has subscribed to
      healthCheck: true # exposes /healthz endpoint
      debugMode: false # verbose logging
    router:
      enabled: true # Allow for built-in router to fan-out event data to forwarders, set to false if there is no need to write data to streams outside of the main one
      # minReplicas: 2 # Override; Defaults to 2 for production, statically 1 for local
      debugMode: true
nginx-ingress:
  enabled: true
cert-manager:
  enabled: false
